name: workflow example
on: 
  schedule: 
    - cron: "0 08 * * *"
  workflow_dispatch:
  push: 
    branches: 
      - master
      - main

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Display the event that triggered the workflow
        run: echo "The job was triggered by a ${{ github.event.name}} event."
      - name: Display runner information
        run: echo "The job is running on ${{ runner.os}} server hosted by github"
      - name: Display information about the repository
        run: echo "The repository of this job is ${{ github.repository}} and the branch use is ${{ github.ref}}"
      - name: checkout the code
        uses: actions/checkout@v2
      - name: set up java
        uses: actions/setup-java@v4
        with: 
          distribution: "microsoft"
          java-version: "21"
      - name: create zip bundle
        run: |
          pwd
          cd /home/runner/work/App4DockerAndCICDAutomation/App4DockerAndCICDAutomation
          zip -r ../${{github.sha}}.zip .
      - name: archieve artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: /home/runner/work/App4DockerAndCICDAutomation/App4DockerAndCICDAutomation
          overwrite: true
